server:
  port: 8080
  context-path: /webApp

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/pizzaproject
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update